// Basic ESLint config for JavaScript (ES2021)
export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        URL: "readonly",
        CustomEvent: "readonly",
        Node: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        ShadowRoot: "readonly",
        CSS: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        atob: "readonly",
        btoa: "readonly",
        crypto: "readonly",
        Event: "readonly",
        SuppressedError: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        NodeFilter: "readonly",
        DocumentFragment: "readonly",
        chrome: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      semi: ["error", "always"],
      quotes: ["error", "double"],
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
    },
  },
];
