export default [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        chrome: "readonly",
        Promise: "readonly",
        setTimeout: "readonly",
        Array: "readonly",
        JSON: "readonly",
        RegExp: "readonly",
        Error: "readonly",
        ShadowRoot: "readonly",
        Node: "readonly",
        CSS: "readonly",
        XMLSerializer: "readonly",
        Image: "readonly",
        btoa: "readonly",
        // Webpack globals
        __webpack_require__: "readonly",
        exports: "readonly",
        // Custom variables that are defined elsewhere
        idName: "readonly",
        action: "readonly",
        props: "readonly",
        detectFieldElements: "readonly",
        displayFieldAugmentation: "readonly",
        continueWithFieldSelection: "readonly",
        startManualFieldSelection: "readonly",
        getCustomSelectorForCurrentDomain: "readonly",
        extractContentData: "readonly",
        continueWithContentSelection: "readonly",
        getFieldName: "readonly",
        getFieldType: "readonly",
        getFieldValue: "readonly",
        getFieldAttributes: "readonly",
        finder_1: "readonly",
        confirmSelectionDialogEl: "writable",
        SMALL_NODE_SIZE: "writable",
        round: "readonly",
        drawMargin: "readonly",
        sleep: "readonly",
        listEl: "writable",
        index: "readonly",
        asyncId: "readonly",
        name: "readonly",
        value: "readonly",
        e: "readonly",
      },
    },
    rules: {
      // Basic rules to catch common issues
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-console": "off", // Allow console statements
    },
  },
];
